/*
================================================================================
                        INTRODUCTION TO SQL - EXAMPLES
================================================================================
This file contains SQL examples for all major RDBMS systems.
Each section is marked with the specific database system.
================================================================================
*/

-- ============================================================================
-- SAMPLE DATABASE SETUP (Run this first)
-- ============================================================================

-- ===================
-- SQL SERVER
-- ===================
/*
CREATE DATABASE ComplexSQL_Tutorial;
GO
USE ComplexSQL_Tutorial;
GO

CREATE TABLE departments (
    department_id INT PRIMARY KEY IDENTITY(1,1),
    department_name VARCHAR(100) NOT NULL,
    manager_id INT,
    location VARCHAR(100)
);

CREATE TABLE employees (
    employee_id INT PRIMARY KEY IDENTITY(1,1),
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    email VARCHAR(100) UNIQUE,
    department_id INT FOREIGN KEY REFERENCES departments(department_id),
    salary DECIMAL(10,2),
    hire_date DATE
);

INSERT INTO departments (department_name, location) VALUES
('Engineering', 'New York'),
('Marketing', 'Los Angeles'),
('Finance', 'Chicago'),
('HR', 'Boston');

INSERT INTO employees (first_name, last_name, email, department_id, salary, hire_date) VALUES
('John', 'Smith', 'john.smith@company.com', 1, 75000.00, '2020-01-15'),
('Jane', 'Doe', 'jane.doe@company.com', 1, 82000.00, '2019-06-20'),
('Bob', 'Johnson', 'bob.johnson@company.com', 2, 65000.00, '2021-03-10'),
('Alice', 'Williams', 'alice.williams@company.com', 3, 90000.00, '2018-11-05'),
('Charlie', 'Brown', 'charlie.brown@company.com', 4, 55000.00, '2022-02-28');
*/

-- ===================
-- ORACLE
-- ===================
/*
CREATE TABLE departments (
    department_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_name VARCHAR2(100) NOT NULL,
    manager_id NUMBER,
    location VARCHAR2(100)
);

CREATE TABLE employees (
    employee_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR2(50) NOT NULL,
    last_name VARCHAR2(50) NOT NULL,
    email VARCHAR2(100) UNIQUE,
    department_id NUMBER REFERENCES departments(department_id),
    salary NUMBER(10,2),
    hire_date DATE
);

INSERT INTO departments (department_name, location) VALUES ('Engineering', 'New York');
INSERT INTO departments (department_name, location) VALUES ('Marketing', 'Los Angeles');
INSERT INTO departments (department_name, location) VALUES ('Finance', 'Chicago');
INSERT INTO departments (department_name, location) VALUES ('HR', 'Boston');

INSERT INTO employees (first_name, last_name, email, department_id, salary, hire_date) VALUES
('John', 'Smith', 'john.smith@company.com', 1, 75000.00, DATE '2020-01-15');
INSERT INTO employees (first_name, last_name, email, department_id, salary, hire_date) VALUES
('Jane', 'Doe', 'jane.doe@company.com', 1, 82000.00, DATE '2019-06-20');
INSERT INTO employees (first_name, last_name, email, department_id, salary, hire_date) VALUES
('Bob', 'Johnson', 'bob.johnson@company.com', 2, 65000.00, DATE '2021-03-10');
INSERT INTO employees (first_name, last_name, email, department_id, salary, hire_date) VALUES
('Alice', 'Williams', 'alice.williams@company.com', 3, 90000.00, DATE '2018-11-05');
INSERT INTO employees (first_name, last_name, email, department_id, salary, hire_date) VALUES
('Charlie', 'Brown', 'charlie.brown@company.com', 4, 55000.00, DATE '2022-02-28');
COMMIT;
*/

-- ===================
-- POSTGRESQL
-- ===================
/*
CREATE TABLE departments (
    department_id SERIAL PRIMARY KEY,
    department_name VARCHAR(100) NOT NULL,
    manager_id INT,
    location VARCHAR(100)
);

CREATE TABLE employees (
    employee_id SERIAL PRIMARY KEY,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    email VARCHAR(100) UNIQUE,
    department_id INT REFERENCES departments(department_id),
    salary DECIMAL(10,2),
    hire_date DATE
);

INSERT INTO departments (department_name, location) VALUES
('Engineering', 'New York'),
('Marketing', 'Los Angeles'),
('Finance', 'Chicago'),
('HR', 'Boston');

INSERT INTO employees (first_name, last_name, email, department_id, salary, hire_date) VALUES
('John', 'Smith', 'john.smith@company.com', 1, 75000.00, '2020-01-15'),
('Jane', 'Doe', 'jane.doe@company.com', 1, 82000.00, '2019-06-20'),
('Bob', 'Johnson', 'bob.johnson@company.com', 2, 65000.00, '2021-03-10'),
('Alice', 'Williams', 'alice.williams@company.com', 3, 90000.00, '2018-11-05'),
('Charlie', 'Brown', 'charlie.brown@company.com', 4, 55000.00, '2022-02-28');
*/

-- ===================
-- MYSQL
-- ===================
/*
CREATE DATABASE ComplexSQL_Tutorial;
USE ComplexSQL_Tutorial;

CREATE TABLE departments (
    department_id INT AUTO_INCREMENT PRIMARY KEY,
    department_name VARCHAR(100) NOT NULL,
    manager_id INT,
    location VARCHAR(100)
);

CREATE TABLE employees (
    employee_id INT AUTO_INCREMENT PRIMARY KEY,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    email VARCHAR(100) UNIQUE,
    department_id INT,
    salary DECIMAL(10,2),
    hire_date DATE,
    FOREIGN KEY (department_id) REFERENCES departments(department_id)
);

INSERT INTO departments (department_name, location) VALUES
('Engineering', 'New York'),
('Marketing', 'Los Angeles'),
('Finance', 'Chicago'),
('HR', 'Boston');

INSERT INTO employees (first_name, last_name, email, department_id, salary, hire_date) VALUES
('John', 'Smith', 'john.smith@company.com', 1, 75000.00, '2020-01-15'),
('Jane', 'Doe', 'jane.doe@company.com', 1, 82000.00, '2019-06-20'),
('Bob', 'Johnson', 'bob.johnson@company.com', 2, 65000.00, '2021-03-10'),
('Alice', 'Williams', 'alice.williams@company.com', 3, 90000.00, '2018-11-05'),
('Charlie', 'Brown', 'charlie.brown@company.com', 4, 55000.00, '2022-02-28');
*/

-- ============================================================================
-- BASIC QUERIES (Works on all RDBMS)
-- ============================================================================

-- Select all columns from a table
SELECT * FROM employees;

-- Select specific columns
SELECT first_name, last_name, salary FROM employees;

-- Filter with WHERE clause
SELECT * FROM employees WHERE department_id = 1;

-- Sort results
SELECT * FROM employees ORDER BY salary DESC;

-- Filter and sort combined
SELECT first_name, last_name, salary 
FROM employees 
WHERE salary > 60000 
ORDER BY salary DESC;

-- ============================================================================
-- AGGREGATE FUNCTIONS (Works on all RDBMS)
-- ============================================================================

-- Count total employees
SELECT COUNT(*) AS total_employees FROM employees;

-- Calculate average salary
SELECT AVG(salary) AS average_salary FROM employees;

-- Find min and max salary
SELECT MIN(salary) AS min_salary, MAX(salary) AS max_salary FROM employees;

-- Sum of all salaries
SELECT SUM(salary) AS total_payroll FROM employees;

-- Group by department
SELECT department_id, COUNT(*) AS emp_count, AVG(salary) AS avg_salary
FROM employees
GROUP BY department_id;
